services:
  agent_logic:
    build:
      context: ./agent_logic_python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./agent_logic_python:/app
    env_file:
      - ./docker.env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    # depends_on:
    #   - whatsapp_handler # Uncomment if agent_logic depends on whatsapp_handler starting first

  whatsapp_handler:
    build:
      context: ./whatsapp_handler_node
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Example port, adjust if needed
    volumes:
      - ./whatsapp_handler_node:/app
      - /app/node_modules # Avoid copying node_modules from host
    restart: unless-stopped
    # depends_on:
    #   - agent_logic # Uncomment if whatsapp_handler depends on agent_logic starting first

  google_calendar_mcp:
    build:
      context: ./google-calendar-mcp
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./google-calendar-mcp/gcp-oauth.keys.json:/app/gcp-oauth.keys.json
    environment:
      - GOOGLE_OAUTH_CREDENTIALS=/app/gcp-oauth.keys.json
      - MCP_SERVER_TRANSPORT=http
      - MCP_SERVER_PORT=8001
    restart: unless-stopped

# You might need to define Dockerfiles for each service
# Create ./agent_logic_python/Dockerfile and ./whatsapp_handler_node/Dockerfile